# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'git-flow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for git-flow

  target 'git-flowTests' do
    inherit! :search_paths
    # Pods for testing
   pod 'AFNetworking', '~> 3.2.1'
  end

  target 'git-flowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
